In [1]:
import numpy as np

In [2]:
a=[1,2,3,4,5]
print(a)

[1, 2, 3, 4, 5]


In [3]:
arr_1=np.array(a)
print(arr_1)

[1 2 3 4 5]


In [4]:
arr_1.shape

(5,)

In [5]:
arr_1.shape[0]

5

In [6]:
arr_1.shape[1]

IndexError: tuple index out of range

In [8]:
arr_1

array([1, 2, 3, 4, 5])

In [9]:
arr_1[3]

4

In [10]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
a2.shape

(3, 3)

In [12]:
a2.shape[0]

3

In [13]:
a2.shape[1]

3

In [14]:
a2.shape[2]

IndexError: tuple index out of range

In [15]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
a2[0][2]

3

In [17]:
type(a2)

numpy.ndarray

# Numpy mathamatic Fuctions

In [18]:
a=np.zeros((4,8))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [19]:
one_array=np.ones((8,10))
one_array

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
full=np.full((5,8),23)
full

array([[23, 23, 23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23, 23, 23]])

In [21]:
iden=np.eye(10)
iden

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [22]:
np.ones_like(a)

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [23]:
full.shape

(5, 8)

In [24]:
np.ones_like(full)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [25]:
np.zeros_like(full)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [26]:
np.full_like(iden,34)

array([[34., 34., 34., 34., 34., 34., 34., 34., 34., 34.],
       [34., 34., 34., 34., 34., 34., 34., 34., 34., 34.],
       [34., 34., 34., 34., 34., 34., 34., 34., 34., 34.],
       [34., 34., 34., 34., 34., 34., 34., 34., 34., 34.],
       [34., 34., 34., 34., 34., 34., 34., 34., 34., 34.],
       [34., 34., 34., 34., 34., 34., 34., 34., 34., 34.],
       [34., 34., 34., 34., 34., 34., 34., 34., 34., 34.],
       [34., 34., 34., 34., 34., 34., 34., 34., 34., 34.],
       [34., 34., 34., 34., 34., 34., 34., 34., 34., 34.],
       [34., 34., 34., 34., 34., 34., 34., 34., 34., 34.]])

In [27]:
np.random.random((3,4))

array([[0.82623785, 0.72640667, 0.00885314, 0.74712146],
       [0.21496987, 0.58739543, 0.49571933, 0.85132296],
       [0.56563526, 0.08287332, 0.56007531, 0.635234  ]])

In [28]:
np.random.randint(20)

8

In [29]:
otp=np.random.randint(1000,9999,3)
otp

array([4185, 8903, 2943])

In [30]:
otp=np.random.randint(1000,9999)
otp

5794

In [31]:
user = 1693

if otp == user:
    print('Transaction success')
else:
    print('Failure, due to incorrect otp')
    

Failure, due to incorrect otp


In [32]:
np.empty([4,5])

array([[1.23559004e-311, 6.27463370e-322, 0.00000000e+000,
        0.00000000e+000, 2.33419537e-312],
       [5.30276956e+180, 1.57076922e-076, 4.57310749e-071,
        3.86068967e-086, 3.35760325e-143],
       [6.01433264e+175, 6.93885958e+218, 5.56218858e+180,
        3.94356143e+180, 2.82983100e-056],
       [6.00124461e-066, 4.08089523e+179, 6.87303535e+169,
        4.92251381e-143, 1.50008929e+248]])

In [33]:
np.random.random((4,5))

array([[0.14354568, 0.67097136, 0.11697612, 0.89312684, 0.15785014],
       [0.51679272, 0.69269364, 0.48598128, 0.34437075, 0.27384908],
       [0.60739989, 0.72954872, 0.99606233, 0.92079905, 0.85738289],
       [0.58879019, 0.60309197, 0.40704923, 0.20435676, 0.07946693]])

Array Subset Creation by slicing

In [34]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
a.shape

(3, 4)

In [36]:
b=a[1:3,:2]
print(b)

[[ 5  6]
 [ 9 10]]


In [37]:
b[0][0]=500

In [38]:
b

array([[500,   6],
       [  9,  10]])

In [39]:
a

array([[  1,   2,   3,   4],
       [500,   6,   7,   8],
       [  9,  10,  11,  12]])

In [40]:
a

array([[  1,   2,   3,   4],
       [500,   6,   7,   8],
       [  9,  10,  11,  12]])

In [41]:
bool_idx=(a>10)
bool_idx

array([[False, False, False, False],
       [ True, False, False, False],
       [False, False,  True,  True]])

In [42]:
c=a[a>10]

In [43]:
c

array([500,  11,  12])

In [44]:
c.shape

(3,)

Array Math

In [45]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(x)
print()
print(y)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


In [46]:
x+y

array([[ 6,  8],
       [10, 12]])

In [47]:
np.add(x,y)

array([[ 6,  8],
       [10, 12]])

In [48]:
x-y

array([[-4, -4],
       [-4, -4]])

In [49]:
np.subtract(x,y)

array([[-4, -4],
       [-4, -4]])

In [50]:
x*y

array([[ 5, 12],
       [21, 32]])

In [51]:
np.multiply(x,y)

array([[ 5, 12],
       [21, 32]])

In [52]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [53]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [54]:
v=np.array([9,10])
w=np.array([11,12])
print(x)
print()
print(y)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


In [55]:
v.dot(w)

219

In [56]:
v*w

array([ 99, 120])

In [57]:
np.dot(v,w)

219

In [58]:
np.dot(x,y)

array([[19, 22],
       [43, 50]])

In [59]:
np.dot(x,v)

array([29, 67])

In [60]:
x*v

array([[ 9, 20],
       [27, 40]])

In [61]:
x

array([[1, 2],
       [3, 4]])

In [62]:
a

array([[  1,   2,   3,   4],
       [500,   6,   7,   8],
       [  9,  10,  11,  12]])

In [63]:
np.sum(a)

573

In [64]:
np.sum(a,axis=0)

array([510,  18,  21,  24])

In [65]:
np.sum(a,axis=1)

array([ 10, 521,  42])

In [66]:
a

array([[  1,   2,   3,   4],
       [500,   6,   7,   8],
       [  9,  10,  11,  12]])

In [67]:
a.T

array([[  1, 500,   9],
       [  2,   6,  10],
       [  3,   7,  11],
       [  4,   8,  12]])

In [68]:
x

array([[1, 2],
       [3, 4]])

In [69]:
y

array([[5, 6],
       [7, 8]])

In [70]:
x.dot(y)

array([[19, 22],
       [43, 50]])

In [71]:
x*y

array([[ 5, 12],
       [21, 32]])

In [72]:
a

array([[  1,   2,   3,   4],
       [500,   6,   7,   8],
       [  9,  10,  11,  12]])

Broadcasting

In [76]:
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v=np.array([1,0,1])
y=np.empty_like(x)
print(x)
print()
print(v)
print()
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[1 0 1]

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [77]:
for i in range(len(x)):
    y[i,:]=x[i,:]+v[:]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


# Combining Arrays

In [78]:
from numpy import array
from numpy import hstack

In [90]:
a1=array([1,2,3])
a2=array([4,5,6])
a3=hstack((a1,a2))
print(a3)

[1 2 3 4 5 6]


In [91]:
from numpy import vstack
a4=vstack((a1,a2))
print(a4)

[[1 2 3]
 [4 5 6]]


In [82]:
print(a3.shape)
print(a4.shape)

(6,)
(2, 3)


In [84]:
a11=array([[1,2,3],[4,5,6]])
a22=array([[11,22,33],[44,55,66]])
a4=hstack((a11,a22))
print(a4)

[[ 1  2  3 11 22 33]
 [ 4  5  6 44 55 66]]


In [85]:
a5=vstack((a11,a22))
print(a5)

[[ 1  2  3]
 [ 4  5  6]
 [11 22 33]
 [44 55 66]]


In [86]:
a5.shape

(4, 3)

In [87]:
a4.shape

(2, 6)

# Reshaping

Converting one dimension of data to another dimension of data

possible ---1d -2d ,2d-3d

not possible --- 1d - 3d , 3d- 2d, 2d - 1d 

method name is 'reshape'

In [92]:
data = array([11,22,33,44,55])
print(data,data.shape)

[11 22 33 44 55] (5,)


In [93]:
data1= data.reshape((data.shape[0],1))
print(data1,data1.shape)

[[11]
 [22]
 [33]
 [44]
 [55]] (5, 1)


In [94]:
data1.shape[0]

5

In [95]:
data1.shape[1]

1

In [97]:
data2=data1.reshape((data1.shape[0],data1.shape[1],1))
print(data2,data2.shape)

[[[11]]

 [[22]]

 [[33]]

 [[44]]

 [[55]]] (5, 1, 1)


In [98]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [99]:
xx=x.reshape((x.shape[0],x.shape[1],1))
print(xx,xx.shape)

[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]] (4, 3, 1)


In [101]:
np.empty_like((2,2))

array([ 67438600, 100729858])

In [102]:
np.empty_like(data)

array([1191669824,        582,          0,          0,          1])

In [103]:
np.empty((2,2))

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [107]:
np.empty_like(([4,3]))

array([1549623048,   75115127])

In [108]:
a

array([[  1,   2,   3,   4],
       [500,   6,   7,   8],
       [  9,  10,  11,  12]])

In [109]:
b

array([[500,   6],
       [  9,  10]])

In [110]:
data

array([11, 22, 33, 44, 55])

In [112]:
df1=data.reshape((data.shape[0],1))
print(df1,df1.shape)

[[11]
 [22]
 [33]
 [44]
 [55]] (5, 1)


In [113]:
df2=x.reshape((x.shape[0],x.shape[1],1))
print(df2,df2.shape)

[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]] (4, 3, 1)


In [114]:
df1

array([[11],
       [22],
       [33],
       [44],
       [55]])

In [115]:
df2

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])