In [2]:
from sklearn import neighbors, datasets, preprocessing 
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score

In [3]:
from sklearn.metrics import mean_absolute_error

In [4]:
iris= datasets.load_iris()

In [5]:

X,y= iris.data[:,:2],iris.target

In [6]:
X

array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6],
       [5.4, 3.9],
       [4.6, 3.4],
       [5. , 3.4],
       [4.4, 2.9],
       [4.9, 3.1],
       [5.4, 3.7],
       [4.8, 3.4],
       [4.8, 3. ],
       [4.3, 3. ],
       [5.8, 4. ],
       [5.7, 4.4],
       [5.4, 3.9],
       [5.1, 3.5],
       [5.7, 3.8],
       [5.1, 3.8],
       [5.4, 3.4],
       [5.1, 3.7],
       [4.6, 3.6],
       [5.1, 3.3],
       [4.8, 3.4],
       [5. , 3. ],
       [5. , 3.4],
       [5.2, 3.5],
       [5.2, 3.4],
       [4.7, 3.2],
       [4.8, 3.1],
       [5.4, 3.4],
       [5.2, 4.1],
       [5.5, 4.2],
       [4.9, 3.1],
       [5. , 3.2],
       [5.5, 3.5],
       [4.9, 3.6],
       [4.4, 3. ],
       [5.1, 3.4],
       [5. , 3.5],
       [4.5, 2.3],
       [4.4, 3.2],
       [5. , 3.5],
       [5.1, 3.8],
       [4.8, 3. ],
       [5.1, 3.8],
       [4.6, 3.2],
       [5.3, 3.7],
       [5. , 3.3],
       [7. , 3.2],
       [6.4, 3.2],
       [6.9,

In [7]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=33)

In [13]:
scaler= preprocessing.StandardScaler().fit(X_train)

In [10]:
scaler

StandardScaler()

In [12]:
X_train

array([[5. , 2.3],
       [4.9, 3.1],
       [6.3, 2.3],
       [5.8, 2.6],
       [6.2, 2.9],
       [4.7, 3.2],
       [4.6, 3.4],
       [5.1, 2.5],
       [4.8, 3.4],
       [7.9, 3.8],
       [5.1, 3.4],
       [5.1, 3.7],
       [5.6, 2.9],
       [6.5, 3. ],
       [5.4, 3.9],
       [7. , 3.2],
       [5.8, 2.8],
       [7.7, 2.6],
       [5.5, 2.5],
       [5.9, 3.2],
       [4.9, 3.6],
       [4.5, 2.3],
       [6.3, 2.8],
       [4.4, 2.9],
       [5. , 3.6],
       [7.2, 3. ],
       [6. , 3.4],
       [6.2, 2.2],
       [7.4, 2.8],
       [6.8, 3. ],
       [6.4, 2.8],
       [5.7, 2.5],
       [5. , 3.5],
       [5.1, 3.8],
       [6.8, 2.8],
       [5.2, 2.7],
       [5.1, 3.8],
       [5.6, 2.5],
       [6.1, 3. ],
       [6.6, 2.9],
       [6.4, 2.8],
       [4.3, 3. ],
       [7.2, 3.6],
       [5.1, 3.5],
       [6.3, 2.5],
       [4.4, 3.2],
       [7.6, 3. ],
       [6.4, 3.2],
       [5.1, 3.8],
       [6.5, 3.2],
       [6.3, 2.7],
       [5. , 3.5],
       [5.2,

In [14]:
X_train=scaler.transform(X_train)

X_test=scaler.transform(X_test)


In [15]:
X_train

array([[-0.91090798, -1.59775374],
       [-1.0271058 ,  0.08448757],
       [ 0.59966379, -1.59775374],
       [ 0.01867465, -0.96691325],
       [ 0.48346596, -0.33607276],
       [-1.25950146,  0.29476773],
       [-1.37569929,  0.71532806],
       [-0.79471015, -1.17719341],
       [-1.14330363,  0.71532806],
       [ 2.45882905,  1.55644871],
       [-0.79471015,  0.71532806],
       [-0.79471015,  1.34616854],
       [-0.21372101, -0.33607276],
       [ 0.83205945, -0.1257926 ],
       [-0.44611666,  1.76672887],
       [ 1.41304859,  0.29476773],
       [ 0.01867465, -0.54635292],
       [ 2.22643339, -0.96691325],
       [-0.32991883, -1.17719341],
       [ 0.13487248,  0.29476773],
       [-1.0271058 ,  1.13588838],
       [-1.49189712, -1.59775374],
       [ 0.59966379, -0.54635292],
       [-1.60809495, -0.33607276],
       [-0.91090798,  1.13588838],
       [ 1.64544425, -0.1257926 ],
       [ 0.25107031,  0.71532806],
       [ 0.48346596, -1.8080339 ],
       [ 1.8778399 ,

In [16]:
X_test

array([[-0.09752318, -0.33607276],
       [ 1.06445511,  0.08448757],
       [-1.25950146,  0.29476773],
       [ 0.83205945, -0.54635292],
       [ 0.36726814, -0.96691325],
       [ 0.59966379,  0.50504789],
       [-1.14330363,  0.71532806],
       [-0.79471015,  0.92560822],
       [ 0.71586162,  0.08448757],
       [ 1.29685076,  0.29476773],
       [ 1.18065293,  0.29476773],
       [-1.60809495, -0.1257926 ],
       [ 0.59966379,  0.71532806],
       [ 0.36726814, -0.33607276],
       [ 1.29685076,  0.08448757],
       [ 0.71586162, -0.33607276],
       [ 0.25107031, -0.1257926 ],
       [-0.67851232,  0.92560822],
       [ 0.59966379,  0.50504789],
       [ 1.64544425,  0.29476773],
       [-1.0271058 ,  0.08448757],
       [-0.09752318,  1.55644871],
       [ 0.83205945, -0.1257926 ],
       [-1.14330363, -0.1257926 ],
       [ 0.25107031, -1.8080339 ],
       [ 0.48346596, -0.54635292],
       [ 0.36726814, -0.1257926 ],
       [ 0.36726814, -0.54635292],
       [ 0.83205945,

In [25]:

knn=neighbors.KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train,y_train)

y_pred= knn.predict(X_test)

accuracy_score=accuracy_score(y_test,y_pred)

mean_error=mean_absolute_error(y_test,y_pred)

TypeError: 'numpy.float64' object is not callable

In [26]:
y_pred

array([1, 1, 0, 2, 1, 2, 0, 0, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0, 2, 2, 0, 0,
       1, 0, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1])

In [19]:
accuracy_score

0.631578947368421

In [20]:
mean_error

0.3684210526315789